version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app:cached
      - ./backend/prisma:/app/prisma:cached
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app:cached
    environment:
      - NODE_ENV=development
