version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./backend/prisma:/app/prisma
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
