name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (root)
        run: npm ci
      - name: Install package dependencies
        run: |
          npm --prefix ${{ matrix.package }} install
      - name: Run lint (if present)
        run: |
          npm --prefix ${{ matrix.package }} run lint || true
      - name: Run tests / build
        run: |
          if [ "${{ matrix.package }}" = "backend" ]; then
            npm --prefix backend run test --if-present || exit 1
          else
            npm --prefix frontend run build --if-present || exit 1
          fi
